### ISSUE TITLE
[Feature]: Home화면 스크롤 로직 변경, 공통 헤더 뷰 로직 변경

### ISSUE THREAD

**Issue by pknujsp** [pknu-wap/2023_1_WAP_APP_TEAM_MEDI#17]
### 📑Feature 설명

<img src="https://user-images.githubusercontent.com/48265129/235387595-0a1063f4-2e33-4166-bf57-95d7fc4ba3a2.png">

화면 전체가 수직 스크롤 되도록 변경

![image](https://user-images.githubusercontent.com/48265129/235387600-72b0bc97-c9ab-4f40-9115-ce282b510def.png)

내용 확장/접기 버튼을 확장 아이콘 버튼 클릭 영역 확대

### 🔲작업 목록

- [x] 화면 전체가 수직 스크롤 되도록 변경
- [x] 내용 확장/접기 버튼을 확장 아이콘 버튼 클릭 영역 확대

### 🕜예상 소요 시간(Optional)

최우선 아님

**Comment by tgyuuAn** [comment]
빨리 해결할 수 있을 것 같아서 제가 해결했습니다!
