### ISSUE TITLE
[Feature]: Node.js 서버 구축

### ISSUE THREAD

**Issue by ho-sick99** [pknu-wap/2023_1_WAP_APP_TEAM_MEDI#18]
### 📑Feature 설명

Express 프레임워크를 사용하여 node.js 서버를 구축합니다.

### 🔲작업 목록
- [x] gitignore 생성
- [x] Node.js 서버 구축
- [x] MCR 패턴 적용
- [x] DB 연동
- [x] 서버 테스트
- [x] 클라우드에 업로드

### ✔️참고 사항(Optional)

로컬에서 구조화된 서버 구축 및 테스팅 이후, 클라우드에 업로드합니다.
개발 기간 동안에는 클라우드의 3000번 포트를 사용합니다.

### 🕜예상 소요 시간(Optional)

5월 1일까지

**Comment by tgyuuAn** [comment]
구우웃입니다
