### ISSUE TITLE
[Refactor]: Penalties 모듈 리팩토링

### ISSUE THREAD

**Issue by tgyuuAn** [pknu-wap/2023_1_WAP_APP_TEAM_MEDI#184]
### 📑Feature 설명

Penalties 모듈 전반적인 리팩토링

### 🔲작업 목록

- [x] Penalties 모듈 리팩터링

### ✔️참고 사항(Optional)

-

### 🕜예상 소요 시간(Optional)

-

**Comment by pknujsp** [comment]
패널티 모듈 내용을 뉴스 모듈로 다 붙여야 할 거 같아요

**Comment by tgyuuAn** [comment]
이거 리팩토링 하면서 그렇게 해놓을게요잉~
