### ISSUE TITLE
안드로이드 프로젝트 설정

### ISSUE THREAD

**Issue by pknujsp** [pknu-wap/2023_1_WAP_APP_TEAM_MEDI#3]
# [ 프로젝트 설정, 라이브러리 등 변경사항 ]

## 📑 작업 리스트

- [x] 사용될 라이브러리 정리
- [x] 사용될 모듈 초기 설정

## 📑 참고사항
- 지속적으로 변경이 생길 수 있습니다.

## 📑 예상 소요 시간
Long time~

**Comment by tgyuuAn** [comment]
구우우웃입니다.
