### ISSUE TITLE
[Feature]: 바텀 네비게이션 visible, invisible 로직 구현

### ISSUE THREAD

**Issue by tgyuuAn** [pknu-wap/2023_1_WAP_APP_TEAM_MEDI#5]
### 📑Feature 설명

SAA에서 하나밖에 없는 액티비티에 들어있는 BottomNavigationView를 Fragment마다 visible할 것인지 invisible할 것인지 정해주는 로직을 구현한다.

### 🔲작업 목록

- [x] MainViewModel 생성하고 Activity에 장착
- [x] 바텀 네비게이션 뷰 관련 로직 작성

### ✔️참고 사항(Optional)

액티비티의 뷰모델을 만들어서 뷰모델에 이벤트를 구현한다. 

### 🕜예상 소요 시간(Optional)

1시간

**Comment by pknujsp** [comment]
확인했습니다
