### ISSUE TITLE
[Feature]: 앱 핵심 Home화면 개발

### ISSUE THREAD

**Issue by pknujsp** [pknu-wap/2023_1_WAP_APP_TEAM_MEDI#6]
### 📑Feature 설명

![](https://user-images.githubusercontent.com/48265129/235302713-27717b57-c2e2-42f8-80b1-071d5676a573.png)

위의 화면을 구현합니다.

클래스명 : HomeFragment

FragmentLayout내에 NestedScrollView를 두고 3개의 Fragment를 보여주는 방식으로 구현 예정입니다.

* 들어갈 자식 fragment이름
  * RecentSearchListFragment
    * 최근 검색 목록
  * RecentCommentListFragment
    * 최근 댓글 목록
  * RecentPenaltyListFragment
    * 행정 처분 목록

위의 프래그먼트는 별개의 모듈들로 제작 예정입니다.

HeaderForElementsView, MediSearchbar 이름으로 공통적으로 사용될 View를 개발합니다.

### 🔲작업 목록

- [x] HomeFragment개발
- [x] RecentSearchListFragment 개발
- [x] RecentCommentListFragment 개발
- [x] RecentPenaltyListFragment 개발
- [x] MediSearchbar라는 이름으로 검색 바 개발
<img width="251" alt="image" src="https://user-images.githubusercontent.com/48265129/235302918-92e203ac-a156-4665-84bf-fcbd6e75a294.png">

- [x] HeaderForElementsView으로 공통 헤더 View 개발
<img width="250" alt="image" src="https://user-images.githubusercontent.com/48265129/235302970-7c089b51-7146-47bf-aa91-c0ecd32105d4.png">

### 🕜예상 소요 시간(Optional)

4월 30일까지

**Comment by tgyuuAn** [comment]
오호라 이슈 작성 너무 꼼꼼하게 하셨는대요..?
보고 배워야겟으요

**Comment by pknujsp** [comment]
### 아래 클래스 추가로 만들었고, 모두 core:ui모듈레 있어요
- 최근 검색 목록의 아이템 뷰로 사용될 ButtonChip
- 행정 처분과 최신 댓글 목록의 아이템 뷰로 사용될 SimpleListView
