### ISSUE TITLE
[Chore]: Refactoring DB Modeling

### ISSUE THREAD

**Issue by winocreative** [pknu-wap/2023_1_WAP_APP_TEAM_MEDI#73]
## 📑 작업 사항 
DB 구조 변경으로 인한 Model 수정

## To-do
- [x] 변경점 수정
- [x] 모델 FK, PK 지정

# #✔️ 기타사항
데이터베이스 중 약에 관한 정보가 변경, 그에 맞게 수정합니다.

**Comment by ho-sick99** [comment]
굿이에요 :)

**Comment by tgyuuAn** [comment]
영웅의 귀환. Hero is back
